// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: grpc/ra.proto

package ra

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            uint64                 `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Req) Reset() {
	*x = Req{}
	mi := &file_grpc_ra_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req) ProtoMessage() {}

func (x *Req) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_ra_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req.ProtoReflect.Descriptor instead.
func (*Req) Descriptor() ([]byte, []int) {
	return file_grpc_ra_proto_rawDescGZIP(), []int{0}
}

func (x *Req) GetTs() uint64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *Req) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type Rep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            uint64                 `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rep) Reset() {
	*x = Rep{}
	mi := &file_grpc_ra_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rep) ProtoMessage() {}

func (x *Rep) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_ra_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rep.ProtoReflect.Descriptor instead.
func (*Rep) Descriptor() ([]byte, []int) {
	return file_grpc_ra_proto_rawDescGZIP(), []int{1}
}

func (x *Rep) GetTs() uint64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

var File_grpc_ra_proto protoreflect.FileDescriptor

const file_grpc_ra_proto_rawDesc = "" +
	"\n" +
	"\rgrpc/ra.proto\x12\x02ra\x1a\x1bgoogle/protobuf/empty.proto\")\n" +
	"\x03Req\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\x04R\x02ts\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\"\x15\n" +
	"\x03Rep\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\x04R\x02ts2^\n" +
	"\x02RA\x12,\n" +
	"\aRequest\x12\a.ra.Req\x1a\x16.google.protobuf.Empty\"\x00\x12*\n" +
	"\x05Reply\x12\a.ra.Rep\x1a\x16.google.protobuf.Empty\"\x00B\fZ\n" +
	"ra/grpc;rab\x06proto3"

var (
	file_grpc_ra_proto_rawDescOnce sync.Once
	file_grpc_ra_proto_rawDescData []byte
)

func file_grpc_ra_proto_rawDescGZIP() []byte {
	file_grpc_ra_proto_rawDescOnce.Do(func() {
		file_grpc_ra_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_ra_proto_rawDesc), len(file_grpc_ra_proto_rawDesc)))
	})
	return file_grpc_ra_proto_rawDescData
}

var file_grpc_ra_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_ra_proto_goTypes = []any{
	(*Req)(nil),           // 0: ra.Req
	(*Rep)(nil),           // 1: ra.Rep
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_grpc_ra_proto_depIdxs = []int32{
	0, // 0: ra.RA.Request:input_type -> ra.Req
	1, // 1: ra.RA.Reply:input_type -> ra.Rep
	2, // 2: ra.RA.Request:output_type -> google.protobuf.Empty
	2, // 3: ra.RA.Reply:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_ra_proto_init() }
func file_grpc_ra_proto_init() {
	if File_grpc_ra_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_ra_proto_rawDesc), len(file_grpc_ra_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_ra_proto_goTypes,
		DependencyIndexes: file_grpc_ra_proto_depIdxs,
		MessageInfos:      file_grpc_ra_proto_msgTypes,
	}.Build()
	File_grpc_ra_proto = out.File
	file_grpc_ra_proto_goTypes = nil
	file_grpc_ra_proto_depIdxs = nil
}
